#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WAIT_LOG="${WAIT_LOG:?set WAIT_LOG}"
WAIT_PATTERN="${WAIT_PATTERN:?set WAIT_PATTERN}"
TARGET_LABEL="${TARGET_LABEL:?set TARGET_LABEL}"
TARGET_SCRIPT="${TARGET_SCRIPT:?set TARGET_SCRIPT}"
NEXT_WAIT_LOG="${NEXT_WAIT_LOG:-}"
NEXT_WAIT_PATTERN="${NEXT_WAIT_PATTERN:-}"
NEXT_TARGET_LABEL="${NEXT_TARGET_LABEL:-}"
NEXT_TARGET_SCRIPT="${NEXT_TARGET_SCRIPT:-}"
TARGET_LOG_PATH="${TARGET_LOG_PATH:-}"
TARGET_RUN_ID="${TARGET_RUN_ID:-}"
TARGET_SEED="${TARGET_SEED:-}"
TARGET_ENV_ASSIGNMENTS="${TARGET_ENV_ASSIGNMENTS:-}"
TARGET_SKIP_IF_LOG_EXISTS="${TARGET_SKIP_IF_LOG_EXISTS:-0}"
NEXT_LOG_PATH="${NEXT_LOG_PATH:-}"
NEXT_RUN_ID="${NEXT_RUN_ID:-}"
NEXT_SEED="${NEXT_SEED:-}"
NEXT_TARGET_ENV_ASSIGNMENTS="${NEXT_TARGET_ENV_ASSIGNMENTS:-}"
NEXT_TARGET_SKIP_IF_LOG_EXISTS="${NEXT_TARGET_SKIP_IF_LOG_EXISTS:-0}"

cd "$ROOT_DIR"

unset STRIDE NGRAM_LAMBDA NGRAM_MAX_N CONFIDENCE_THRESHOLD GATE_MODE MIN_COUNT APPLY_MODE
unset LAMBDA_SCHEDULE CONFIDENCE_SCHEDULE ORDER_LAMBDAS PACKED_CACHE BATCH_SEQS BIGRAM_VOCAB_SIZE
unset VALUE_RESIDUAL MAX_WINDOWS CACHE_KIND HASHED_BUCKETS NGRAM_ADAPT_ENABLED NGRAM_ADAPT_LR
unset NGRAM_ADAPT_DECAY NGRAM_ADAPT_LAST_N_BLOCKS CANDIDATE ARTIFACT_PATH TEMPLATE_PATH TRAIN_GPT_PATH

while ! rg -q "$WAIT_PATTERN" "$WAIT_LOG" 2>/dev/null; do
  sleep 60
done

if [[ -n "$NEXT_TARGET_SCRIPT" ]]; then
  WAIT_LOG="$NEXT_WAIT_LOG" \
  WAIT_PATTERN="$NEXT_WAIT_PATTERN" \
  TARGET_LABEL="$NEXT_TARGET_LABEL" \
  TARGET_SCRIPT="$NEXT_TARGET_SCRIPT" \
  TARGET_LOG_PATH="$NEXT_LOG_PATH" \
  TARGET_RUN_ID="$NEXT_RUN_ID" \
  TARGET_SEED="$NEXT_SEED" \
  TARGET_ENV_ASSIGNMENTS="$NEXT_TARGET_ENV_ASSIGNMENTS" \
  TARGET_SKIP_IF_LOG_EXISTS="$NEXT_TARGET_SKIP_IF_LOG_EXISTS" \
  setsid bash "$ROOT_DIR/scripts/after_log_launch_script.sh" >/tmp/h200_after_${TARGET_LABEL}_launch_${NEXT_TARGET_LABEL}.log 2>&1 < /dev/null &
fi

if [[ -n "$TARGET_LOG_PATH" ]]; then
  export LOG_PATH="$TARGET_LOG_PATH"
fi
if [[ -n "$TARGET_RUN_ID" ]]; then
  export RUN_ID="$TARGET_RUN_ID"
fi
if [[ -n "$TARGET_SEED" ]]; then
  export SEED="$TARGET_SEED"
fi

if [[ "$TARGET_SKIP_IF_LOG_EXISTS" == "1" ]] && [[ -n "$TARGET_LOG_PATH" ]] && [[ -f "$TARGET_LOG_PATH" ]]; then
  exit 0
fi

if [[ -n "$TARGET_ENV_ASSIGNMENTS" ]]; then
  read -r -a target_env <<< "$TARGET_ENV_ASSIGNMENTS"
  exec env "${target_env[@]}" bash "$TARGET_SCRIPT"
fi

exec bash "$TARGET_SCRIPT"
