#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
RUN_DIR="$ROOT_DIR/records/track_non_record_16mb/2026-03-24_H200_LeakyReLU_LegalTTT_FlashFallback"
LOG_DIR="$RUN_DIR/logs"

WAIT_RECORD674_LOG="${WAIT_RECORD674_LOG:?set WAIT_RECORD674_LOG}"
WAIT_PATTERN="${WAIT_PATTERN:-^final_(ngram_eval_exact|int6_sliding_window_ngram[0-9]+_exact) val_loss:}"
TARGET_ARCH_CANDIDATE="${TARGET_ARCH_CANDIDATE:?set TARGET_ARCH_CANDIDATE}"
TARGET_PROXY_TRAIN_LOG="${TARGET_PROXY_TRAIN_LOG:?set TARGET_PROXY_TRAIN_LOG}"
TARGET_PROXY_ARTIFACT_PT="${TARGET_PROXY_ARTIFACT_PT:?set TARGET_PROXY_ARTIFACT_PT}"
TARGET_PROXY_ARTIFACT_INT6="${TARGET_PROXY_ARTIFACT_INT6:?set TARGET_PROXY_ARTIFACT_INT6}"
TARGET_RECORD674_LOG="${TARGET_RECORD674_LOG:?set TARGET_RECORD674_LOG}"
TARGET_RECORD674_LAM18_SMOKE_LOG="${TARGET_RECORD674_LAM18_SMOKE_LOG:?set TARGET_RECORD674_LAM18_SMOKE_LOG}"
TARGET_RECORD674_LAM22_SMOKE_LOG="${TARGET_RECORD674_LAM22_SMOKE_LOG:?set TARGET_RECORD674_LAM22_SMOKE_LOG}"
TARGET_RECORD674_MIN3_SMOKE_LOG="${TARGET_RECORD674_MIN3_SMOKE_LOG:?set TARGET_RECORD674_MIN3_SMOKE_LOG}"
TARGET_CONF07_LOG="${TARGET_CONF07_LOG:-$LOG_DIR/h200_artifact_ngram_record659_conf07_h100proxy7185_${TARGET_ARCH_CANDIDATE}_seed1337.txt}"
SEED="${SEED:-1337}"
RUN_NEARBY_SMOKES="${RUN_NEARBY_SMOKES:-1}"
RUN_CONF07_TAIL="${RUN_CONF07_TAIL:-0}"
NEXT_ARCH_CANDIDATE="${NEXT_ARCH_CANDIDATE:-}"
NEXT_WAIT_RECORD674_LOG="${NEXT_WAIT_RECORD674_LOG:-}"
NEXT_PROXY_TRAIN_LOG="${NEXT_PROXY_TRAIN_LOG:-}"
NEXT_PROXY_ARTIFACT_PT="${NEXT_PROXY_ARTIFACT_PT:-}"
NEXT_PROXY_ARTIFACT_INT6="${NEXT_PROXY_ARTIFACT_INT6:-}"
NEXT_RECORD674_LOG="${NEXT_RECORD674_LOG:-}"
NEXT_RECORD674_LAM18_SMOKE_LOG="${NEXT_RECORD674_LAM18_SMOKE_LOG:-}"
NEXT_RECORD674_LAM22_SMOKE_LOG="${NEXT_RECORD674_LAM22_SMOKE_LOG:-}"
NEXT_RECORD674_MIN3_SMOKE_LOG="${NEXT_RECORD674_MIN3_SMOKE_LOG:-}"
NEXT_CONF07_LOG="${NEXT_CONF07_LOG:-}"

cd "$ROOT_DIR"
source .venv/bin/activate

while ! rg -q "$WAIT_PATTERN" "$WAIT_RECORD674_LOG" 2>/dev/null; do
  sleep 60
done

if [[ -n "$NEXT_ARCH_CANDIDATE" ]]; then
  WAIT_RECORD674_LOG="$NEXT_WAIT_RECORD674_LOG" \
  WAIT_PATTERN="$WAIT_PATTERN" \
  TARGET_ARCH_CANDIDATE="$NEXT_ARCH_CANDIDATE" \
  TARGET_PROXY_TRAIN_LOG="$NEXT_PROXY_TRAIN_LOG" \
  TARGET_PROXY_ARTIFACT_PT="$NEXT_PROXY_ARTIFACT_PT" \
  TARGET_PROXY_ARTIFACT_INT6="$NEXT_PROXY_ARTIFACT_INT6" \
  TARGET_RECORD674_LOG="$NEXT_RECORD674_LOG" \
  TARGET_RECORD674_LAM18_SMOKE_LOG="$NEXT_RECORD674_LAM18_SMOKE_LOG" \
  TARGET_RECORD674_LAM22_SMOKE_LOG="$NEXT_RECORD674_LAM22_SMOKE_LOG" \
  TARGET_RECORD674_MIN3_SMOKE_LOG="$NEXT_RECORD674_MIN3_SMOKE_LOG" \
  TARGET_CONF07_LOG="$NEXT_CONF07_LOG" \
  RUN_NEARBY_SMOKES="$RUN_NEARBY_SMOKES" \
  RUN_CONF07_TAIL="$RUN_CONF07_TAIL" \
  nohup bash "$ROOT_DIR/scripts/after_record674_launch_arch.sh" >/tmp/h200_after_${TARGET_ARCH_CANDIDATE}_record674_launch_${NEXT_ARCH_CANDIDATE}.log 2>&1 < /dev/null &
fi

PROXY_TRAIN_LOG="$TARGET_PROXY_TRAIN_LOG" \
PROXY_ARTIFACT_PT="$TARGET_PROXY_ARTIFACT_PT" \
PROXY_ARTIFACT_INT6="$TARGET_PROXY_ARTIFACT_INT6" \
PROXY_RECORD674_LOG="$TARGET_RECORD674_LOG" \
PROXY_RECORD674_LAM18_SMOKE_LOG="$TARGET_RECORD674_LAM18_SMOKE_LOG" \
PROXY_RECORD674_LAM22_SMOKE_LOG="$TARGET_RECORD674_LAM22_SMOKE_LOG" \
PROXY_RECORD674_MIN3_SMOKE_LOG="$TARGET_RECORD674_MIN3_SMOKE_LOG" \
PROXY_CONF07_LOG="$TARGET_CONF07_LOG" \
RUN_NEARBY_SMOKES="$RUN_NEARBY_SMOKES" \
RUN_CONF07_TAIL="$RUN_CONF07_TAIL" \
setsid bash "$ROOT_DIR/scripts/after_proxy_train_run_record674_then_conf07.sh" >/tmp/h200_after_${TARGET_ARCH_CANDIDATE}_proxy_train_record674.log 2>&1 < /dev/null &

ARCH_CANDIDATE="$TARGET_ARCH_CANDIDATE" \
SEED="$SEED" \
bash "$ROOT_DIR/scripts/icrn_h200_ttt_h100_proxy_candidate.sh" >"$TARGET_PROXY_TRAIN_LOG" 2>&1
