#!/usr/bin/env bash
set -euo pipefail

export TTT_ENABLED="${TTT_ENABLED:-0}"
export NGRAM_EVAL_ENABLED="${NGRAM_EVAL_ENABLED:-1}"
export NGRAM_STRIDE="${NGRAM_STRIDE:-128}"
export NGRAM_BATCH_SEQS="${NGRAM_BATCH_SEQS:-32}"
export NGRAM_CACHE_KIND="${NGRAM_CACHE_KIND:-exact}"
export NGRAM_HASHED_BUCKETS="${NGRAM_HASHED_BUCKETS:-4194304}"
export NGRAM_LAMBDA="${NGRAM_LAMBDA:-0.15}"
export NGRAM_MAX_N="${NGRAM_MAX_N:-5}"
export NGRAM_CONFIDENCE_THRESHOLD="${NGRAM_CONFIDENCE_THRESHOLD:-0.5}"
export NGRAM_APPLY_MODE="${NGRAM_APPLY_MODE:-improve_only}"
export NGRAM_MIN_COUNT="${NGRAM_MIN_COUNT:-3}"
export NGRAM_PACKED_CACHE="${NGRAM_PACKED_CACHE:-1}"
export NGRAM_GLOBAL_CACHE="${NGRAM_GLOBAL_CACHE:-1}"

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
exec bash "$ROOT_DIR/scripts/h100_repro_leaky_ttt_parallel_muon.sh"
